/**
 * @swagger
 * paths:
 *    /login:
 *     post:
 *       summary: WiNGS Users can generate API key only from WiNGS UI. WiNGS UI -> Click user icon -> Generate API Key --> Create API Key 
 *       tags: [Authentication]
 *       description: WiNGS User does not have direct access to this API.Details are provided only for informational purpose.
 *                    Fetch the WiNGS API token to access API. Only 1 token can be generated by a WiNGS User. Tokens are credentials, please store them properly. We don't store tokens and you cannot fetch the token again using WiNGS interface.
 *       requestBody:
 *         required: true
 *         content:
 *           application/json:
 *             schema:
 *               $ref: '#components/schemas/Auth'
 *               
 *       responses: 
 *         "200":
 *           description : "successful operation"
 *           headers:
 *             Access-Control-Allow-Origin:
 *               schema:
 *                 type: string
 *           content:
 *             application/json:
 *               schema:
 *                 $ref: '#components/schemas/login_resp'
 *         "403":
 *           description: "Reached Token Limit.Cannot generate new tokens" 
 *    /revoke:
 *     post:
 *       summary: WiNGS User can revoke API key only from WiNGS UI. WiNGS UI -> Click user icon -> Generate API Key --> Revoke API Key
 *       security:
 *         - jwt: []
 *       tags: [Authentication]
 *       description: WiNGS User does not have direct access to this API.Details are provided only for informational purpose.
 *                    User can revoke the token which is used as the Bearer Token
 *               
 *       responses: 
 *         "200":
 *           description : "successful operation-Token revoked"
 *         "401":
 *           description : "Unauthorized-Revoked Token"
 *    /revoke?:
 *     post:
 *       summary: WiNGS Revoke Token-Admin privilege
 *       security:
 *         - jwt: []
 *       tags: [Authentication]
 *       description: WiNGS User does not have direct access to this API.Details are provided only for informational purpose.
 *                    WiNGS Admin will be provided access if required.Admin can revoke the token of the user within his center
 *       parameters:
 *         - in: query
 *           name: type
 *           type: integer
 *           value: admin
 *           description: admin is the only supported value. Token bearer should be admin of the center
 *       requestBody:
 *         required: true
 *         content:
 *           application/json:
 *             schema:
 *               $ref: '#components/schemas/user'           
 *       responses: 
 *         "200":
 *           description : "successful operation-Token revoked"
 *         "401":
 *           description : "Unauthorized-Revoked Token"
 *    /regenerate:
 *     post:
 *       summary: Forgot WiNGS Token - Regenerate
 *       tags: [Authentication]
 *       description: WiNGS User does not have direct access to this API.Details are provided only for informational purpose. 
 *                    Allows only 2 attempts.Forgot token endpoint can be used to generate a new token when the old token is lost
 *       requestBody:
 *         required: true
 *         content:
 *           application/json:
 *             schema:
 *               $ref: '#components/schemas/Auth'
 *               
 *       responses: 
 *         "200":
 *           description : "successful operation"
 *           content:
 *             application/json:
 *               schema:
 *                 $ref: '#components/schemas/login_resp'
 *         "403":
 *           description: "Reached Forgot Token Limit. Cannot generate new tokens" 
  *    /reactivate:
 *     post:
 *       summary: WiNGS Revoke Token-Admin privilege
 *       security:
 *         - jwt: []
 *       tags: [Authentication]
 *       description: WiNGS User does not have direct access to this API.Details are provided only for informational purpose. 
 *                   WiNGS Admin will be provided access if needed.Admin can reactivate API access for the user mentioned in the request body
 *       parameters:
 *         - in: query
 *           name: type
 *           type: integer
 *           value: admin
 *           description: admin is the only supported value. Token bearer should be admin of the center
 *       requestBody:
 *         required: true
 *         content:
 *           application/json:
 *             schema:
 *               $ref: '#components/schemas/user'           
 *       responses: 
 *         "200":
 *           description : "success"
 *         "401":
 *           description : "Unauthorized-Revoked Token"
 * components:
 *     schemas:
 *       Auth:
 *         allOf:
 *           $ref: '#/components/schemas/user'
 *           type: object
 *           required:
 *             - center_id
 *           properties:
 *             center_id:
 *               type: integer
 *               description: WiNGS Center ID
 *               example: 3
 *       user:
 *         type: object
 *         required:
 *           - user_id
 *         properties:
 *           user_id:
 *             type: integer
 *             description: WiNGS User ID
 *             example: 1084
 *       login_resp:
 *         type: object
 *         properties:
 *           message:
 *             type: string
 *             description: WiNGS User API Access Token
 *             example: dsdksjdkjskdjsk.jhdsdhjshdjshdjs.kdjskdjksjdksjdksjkj
 */
